# Generated by Django 2.2.7 on 2019-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg', models.DateTimeField()),
                ('expiry', models.DateTimeField()),
                ('firm_name', models.ForeignKey(on_delete=None, related_name='damage_customer', to='gnb.Customer')),
                ('name', models.ForeignKey(on_delete=None, related_name='damage_customer_name', to='gnb.Customer')),
                ('product', models.ForeignKey(on_delete=None, related_name='damage_product', to='gnb.Product')),
            ],
        ),
    ]
