# Generated by Django 2.2.7 on 2019-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnb', '0002_auto_20191111_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='firm_name',
            field=models.ForeignKey(on_delete=None, related_name='damage_firm_name', to='gnb.Customer'),
        ),
    ]
