# Generated by Django 2.2.7 on 2019-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnb', '0004_auto_20191111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='name',
            field=models.ForeignKey(on_delete=None, related_name='damage_customer_name', to='gnb.Customer'),
        ),
    ]
