# Generated by Django 2.2.7 on 2019-11-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=4000)),
                ('university', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('work_experience', models.TextField(max_length=4000)),
            ],
        ),
    ]
